<a href="https://colab.research.google.com/github/Trishti-s/Deep_Learning/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [3]:
from google.colab import files
import zipfile
import os

uploaded = files.upload()

zip_file_name = list(uploaded.keys())[0]

with zipfile.ZipFile(zip_file_name, 'r') as zip_ref:
    zip_ref.extractall('./abalone_data')

data_file_path = os.path.join('./abalone_data', 'abalone.data')

data = pd.read_csv(data_file_path, header=None)
data.head()

Saving abalone.zip to abalone (1).zip

   0      1      2      3       4       5       6      7   8
0  M  0.455  0.365  0.095  0.5140  0.2245  0.1010  0.150  15
1  M  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.070   7
2  F  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.210   9
3  M  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.155  10
4  I  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.055   7

In [4]:
data.columns=[
    "Sex","Length","Diameter","Height","Whole_weight",
    "Shucked_weight","Viscera_weight","Shell_weight","Rings"
]

data.head()

,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [26]:
X=data.drop("Rings",axis=1).values
y=data["Rings"].values.reshape(-1,1)

In [27]:
scaler=StandardScaler()
X=scaler.fit_transform(X)

In [28]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [32]:
def sigmoid(x):
    x=np.clip(x,-500,500)
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return x*(1-x)

In [33]:
input_size=X_train.shape[1]
hidden_size=8
output_size=1

np.random.seed(42)

W1=np.random.randn(input_size,hidden_size)*0.01
b1=np.zeros((1,hidden_size))

W2=np.random.randn(hidden_size,output_size)*0.01
b2=np.zeros((1,output_size))

In [34]:
lr=0.0001
epochs=1000

for epoch in range(epochs):

    hidden_input=np.dot(X_train,W1)+b1
    hidden_output=sigmoid(hidden_input)

    final_input=np.dot(hidden_output,W2)+b2
    final_output=final_input

    error=y_train-final_output

    d_output=error
    d_hidden=np.dot(d_output,W2.T)*sigmoid_derivative(hidden_output)

    W2+=lr*np.dot(hidden_output.T,d_output)
    b2+=lr*np.sum(d_output,axis=0,keepdims=True)

    W1+=lr*np.dot(X_train.T,d_hidden)
    b1+=lr*np.sum(d_hidden,axis=0,keepdims=True)

    if epoch%100==0:
        loss=np.mean(error**2)
        print("Epoch:",epoch,"Loss:",loss)

Epoch: 0 Loss: 109.07664202151261
Epoch: 100 Loss: 4.88728404159461
Epoch: 200 Loss: 4.637768908730667
Epoch: 300 Loss: 4.51910687743155
Epoch: 400 Loss: 4.4232265153687615
Epoch: 500 Loss: 4.375776639940963
Epoch: 600 Loss: 4.336490376413631
Epoch: 700 Loss: 4.303139933435906
Epoch: 800 Loss: 4.271968959685335
Epoch: 900 Loss: 4.242382137329714

In [35]:
hidden_input=np.dot(X_test,W1)+b1
hidden_output=sigmoid(hidden_input)

final_input=np.dot(hidden_output,W2)+b2
predictions=final_input

In [37]:
mse = np.mean((y_test - predictions)**2)
print("Mean Squared Error:", mse)

Mean Squared Error: 4.4143425171832416